### ISSUE TITLE
[BUG] Line Module Channel unable to attach bot to the line module

### ISSUE THREAD

**Issue by fuzzy28** [line/line-bot-sdk-java#1095]
## Bug Report

**Describe the bug**
I'm using sdk below, I'm getting 400 BAD REQUEST error when attaching the bot to the line module channel, IT WORKS when using POSTMAN but not through the library. Maybe because the library URL encodes the request body? 

    <dependency>
      <groupId>com.linecorp.bot</groupId>
      <artifactId>line-bot-spring-boot-client</artifactId>
      <version>7.8.0</version>
    </dependency>

Getting below error without the log on what's the error from the response body of the API Call

`Caused by: com.linecorp.bot.moduleattach.client.LineModuleAttachClientException: API returns error: code=400 requestUrl=https://manager.line.biz/module/auth/v1/token requestId=null 
	at com.linecorp.bot.moduleattach.client.LineModuleAttachExceptionBuilder.buildException(LineModuleAttachExceptionBuilder.java:32)
	at com.linecorp.bot.client.base.AbstractExceptionBuilder.build(AbstractExceptionBuilder.java:43)
	at com.linecorp.bot.client.base.ApiClientBuilder.lambda$build$1(ApiClientBuilder.java:215)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at com.linecorp.bot.client.base.http.HttpChain.proceed(HttpChain.java:35)
	at com.linecorp.bot.client.base.HeaderInterceptor.intercept(HeaderInterceptor.java:47)
	at com.linecorp.bot.client.base.ApiClientBuilder.lambda$addInterceptor$0(ApiClientBuilder.java:136)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)`

**To Reproduce**

1. Attach bot to module using the client library

**Expected behavior**
Successfully attach bot to module channel

**Screenshots**

**Environment (please complete the following information):**
 - OS: MacOs
 - JDK Version: Open JDK 17
 - line-bot-sdk-java version(s): 7.8.0

**Comment by fuzzy28** [comment]
Issue has been fixed after adding  ApiAuthenticatedClientBuilder
`.addAuthenticationHeader(false)` in the
