### ISSUE TITLE
ClassCastException in Spring Boot 2 

### ISSUE THREAD

**Issue by uptown** [line/line-bot-sdk-java#189]
`java.lang.ClassCastException: org.springframework.web.servlet.resource.ResourceHttpRequestHandler cannot be cast to org.springframework.web.method.HandlerMethod
        at com.linecorp.bot.spring.boot.interceptor.LineBotServerInterceptor.preHandle(LineBotServerInterceptor.java:49)
        at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:136)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:986)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:870)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:855)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)`

During I build my server with spring boot 2, I found a problem, which indicates `preHandle` method in  `LineBotServerInterceptor` should be able to handle `ResourceHttpRequestHandler`. 

I solved this problem with overriding ResourceHttpRequestHandler file in my project.

I think it is better that checking  the 3rd parameter's type before casting that parameter to HandlerMethod forcely.

**Comment by kazuki-ma** [comment]
This issue fixed in https://github.com/line/line-bot-sdk-java/pull/194
