### ISSUE TITLE
[BUG]: LINE Spring boot module doesn't support version 2.2.4 or 2.3.0.M1

### ISSUE THREAD

**Issue by liefra** [line/line-bot-sdk-java#437]
## Bug Report
When I try to run the LINE Spring boot module with Spring Boot WebMVC version `2.2.4` or `2.3.0.M1` the `@LineMessageHandler` throws a `NullPointerException`. The same code works well with `2.1.12.RELEASE`.

**To Reproduce**
If you add `id("org.springframework.boot") version "2.2.4.RELEASE"` to `gradle.build`

**Expected behavior**
`LineMessageHandler` retrieves the incoming message.

**Log**
```
2020-02-01T01:34:52.962993+00:00 app[web.1]: 2020-02-01 01:34:52.962 ERROR 4 --- [io-34930-exec-4] c.l.b.s.b.s.LineMessageHandlerSupport    : null
2020-02-01T01:34:52.963031+00:00 app[web.1]:
2020-02-01T01:34:52.963034+00:00 app[web.1]: java.lang.NullPointerException: null
2020-02-01T01:34:52.963037+00:00 app[web.1]: at com.linecorp.bot.spring.boot.support.LineMessageHandlerSupport.dispatchInternal(LineMessageHandlerSupport.java:187) ~[line-bot-spring-boot-3.3.1.jar!/:3.3.1]
2020-02-01T01:34:52.963039+00:00 app[web.1]: at com.linecorp.bot.spring.boot.support.LineMessageHandlerSupport.dispatch(LineMessageHandlerSupport.java:177) ~[line-bot-spring-boot-3.3.1.jar!/:3.3.1]
2020-02-01T01:34:52.963041+00:00 app[web.1]: at java.base/java.util.ArrayList.forEach(ArrayList.java:1507) ~[na:na]
2020-02-01T01:34:52.963044+00:00 app[web.1]: at com.linecorp.bot.spring.boot.support.LineMessageHandlerSupport.callback(LineMessageHandlerSupport.java:171) ~[line-bot-spring-boot-3.3.1.jar!/:3.3.1]
2020-02-01T01:34:52.963046+00:00 app[web.1]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
2020-02-01T01:34:52.963048+00:00 app[web.1]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
2020-02-01T01:34:52.963050+00:00 app[web.1]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
2020-02-01T01:34:52.963052+00:00 app[web.1]: at java.base/java.lang.reflect.Method.invoke(Method.java:567) ~[na:na]
2020-02-01T01:34:52.963054+00:00 app[web.1]: at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
2020-02-01T01:34:52.963057+00:00 app[web.1]: at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
2020-02-01T01:34:52.963061+00:00 app[web.1]: at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
2020-02-01T01:34:52.963063+00:00 app[web.1]: at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888) ~[spring-webmvc-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
2020-02-01T01:34:52.963065+00:00 app[web.1]: at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793) ~[spring-webmvc-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
2020-02-01T01:34:52.963067+00:00 app[web.1]: at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
2020-02-01T01:34:52.963069+00:00 app[web.1]: at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
2020-02-01T01:34:52.963071+00:00 app[web.1]: at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
2020-02-01T01:34:52.963073+00:00 app[web.1]: at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
2020-02-01T01:34:52.963075+00:00 app[web.1]: at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
2020-02-01T01:34:52.963078+00:00 app[web.1]: at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
2020-02-01T01:34:52.963080+00:00 app[web.1]: at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
2020-02-01T01:34:52.963082+00:00 app[web.1]: at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
2020-02-01T01:34:52.963084+00:00 app[web.1]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
2020-02-01T01:34:52.963086+00:00 app[web.1]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
2020-02-01T01:34:52.963088+00:00 app[web.1]: at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.30.jar!/:9.0.30]
2020-02-01T01:34:52.963090+00:00 app[web.1]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
2020-02-01T01:34:52.963091+00:00 app[web.1]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
2020-02-01T01:34:52.963093+00:00 app[web.1]: at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
2020-02-01T01:34:52.963095+00:00 app[web.1]: at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
2020-02-01T01:34:52.963105+00:00 app[web.1]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
2020-02-01T01:34:52.963107+00:00 app[web.1]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
2020-02-01T01:34:52.963109+00:00 app[web.1]: at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
2020-02-01T01:34:52.963111+00:00 app[web.1]: at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
2020-02-01T01:34:52.963113+00:00 app[web.1]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
2020-02-01T01:34:52.963115+00:00 app[web.1]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
2020-02-01T01:34:52.963117+00:00 app[web.1]: at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:108) ~[spring-boot-actuator-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
2020-02-01T01:34:52.963119+00:00 app[web.1]: at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
2020-02-01T01:34:52.963121+00:00 app[web.1]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
2020-02-01T01:34:52.963123+00:00 app[web.1]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
2020-02-01T01:34:52.963126+00:00 app[web.1]: at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
2020-02-01T01:34:52.963128+00:00 app[web.1]: at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
2020-02-01T01:34:52.963130+00:00 app[web.1]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
2020-02-01T01:34:52.963132+00:00 app[web.1]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
2020-02-01T01:34:52.963134+00:00 app[web.1]: at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
2020-02-01T01:34:52.963136+00:00 app[web.1]: at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
2020-02-01T01:34:52.963138+00:00 app[web.1]: at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
2020-02-01T01:34:52.963140+00:00 app[web.1]: at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
2020-02-01T01:34:52.963142+00:00 app[web.1]: at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
2020-02-01T01:34:52.963144+00:00 app[web.1]: at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
2020-02-01T01:34:52.963146+00:00 app[web.1]: at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
2020-02-01T01:34:52.963148+00:00 app[web.1]: at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
2020-02-01T01:34:52.963150+00:00 app[web.1]: at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
2020-02-01T01:34:52.963152+00:00 app[web.1]: at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
2020-02-01T01:34:52.963154+00:00 app[web.1]: at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
2020-02-01T01:34:52.963156+00:00 app[web.1]: at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1598) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
2020-02-01T01:34:52.963158+00:00 app[web.1]: at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
2020-02-01T01:34:52.963160+00:00 app[web.1]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
2020-02-01T01:34:52.963163+00:00 app[web.1]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
2020-02-01T01:34:52.963165+00:00 app[web.1]: at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.30.jar!/:9.0.30]
2020-02-01T01:34:52.963167+00:00 app[web.1]: at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
2020-02-01T01:34:52.963169+00:00 app[web.1]:
```

**Environment (please complete the following information):**
 - OS: CentOS
 - JDK Version: Tested 8/11/13
 - line-bot-sdk-java version(s) **3.3.1**

**Comment by tokuhirom** [comment]
we can't reproduce your issue.

**Comment by imasahiro** [comment]
@liefra Thanks for filing an issue. Could you tell me which spring-framework and spring-boot dependency actually your application pulls?

**Comment by liefra** [comment]
@imasahiro: Thank you for having a look at this.

The application works fine with `2.1.12.RELEASE`, but I get a `NullPointerException` when I change to a newer version of Spring Boot `2.2.4` or `2.3.0.M1`.

It is a Kotlin Spring Boot app. The gradle dependencies are:
```
implementation("org.springframework.boot:spring-boot-starter-actuator")
implementation("org.springframework.boot:spring-boot-starter-web")
implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
implementation("org.jetbrains.kotlin:kotlin-reflect")
implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

implementation("com.linecorp.bot:line-bot-spring-boot:3.3.1")
```

**Comment by imasahiro** [comment]
@liefra Thanks for info but hm.. I cannot reproduce this yet without reproducer. Is it possible to provide us a simple reproducible code?

**Comment by liefra** [comment]
@imasahiro: While creating a small demo app I realised that the issue **only** occurs when using the `spring.main.lazy-initialization=true` feature of Spring Boot 2.1 and above.

So probably it is not a bug, but just a misuse from my side. 

See my demo project here: https://github.com/liefra/line-issue-437

Thank you and sorry for the false alarm.

**Comment by kazuki-ma** [comment]
@liefra 

Thank you for your reporting. We want add this as limitation now.
Track https://github.com/line/line-bot-sdk-java/issues/456 for documentation status.
