### ISSUE TITLE
[Feature Request] Doc / example about how to use `LineMessagingServiceBuilder` to enable proxy in line-bot-spring-boot

### ISSUE THREAD

**Issue by jiangying000** [line/line-bot-sdk-java#916]
I am building bot following https://github.com/line/line-bot-sdk-java/tree/bbfeb9989f1e17add0798a8bbc8eccf94849d221/sample-spring-boot-echo and encounter error:
```
2023-03-12 10:19:07.078  INFO 29512 --- [api.line.me/...] com.linecorp.bot.client.wire             : <-- HTTP FAILED: java.net.SocketTimeoutException: connect timed out
2023-03-12 10:19:07.078  WARN 29512 --- [api.line.me/...] c.l.b.s.b.s.ReplyByReturnValueConsumer   : Reply message failed: connect timed out

com.linecorp.bot.client.exception.GeneralLineMessagingException: connect timed out
	at com.linecorp.bot.client.LineMessagingClientImpl$BotApiCallbackAdaptor.onFailure(LineMessagingClientImpl.java:444) ~[line-bot-api-client-5.0.3.jar:5.0.3]
	at retrofit2.OkHttpCall$1.callFailure(OkHttpCall.java:175) ~[retrofit-2.9.0.jar:na]
	at retrofit2.OkHttpCall$1.onFailure(OkHttpCall.java:170) ~[retrofit-2.9.0.jar:na]
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525) ~[okhttp-4.9.3.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method) ~[na:na]
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237) ~[na:na]
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:609) ~[na:na]
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128) ~[okhttp-4.9.3.jar:na]
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295) ~[okhttp-4.9.3.jar:na]
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207) ~[okhttp-4.9.3.jar:na]
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226) ~[okhttp-4.9.3.jar:na]
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106) ~[okhttp-4.9.3.jar:na]
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74) ~[okhttp-4.9.3.jar:na]
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255) ~[okhttp-4.9.3.jar:na]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) ~[okhttp-4.9.3.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.3.jar:na]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[okhttp-4.9.3.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.3.jar:na]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.9.3.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.3.jar:na]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.9.3.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.3.jar:na]
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221) ~[logging-interceptor-4.9.3.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.3.jar:na]
	at com.linecorp.bot.client.HeaderInterceptor.intercept(HeaderInterceptor.java:39) ~[line-bot-api-client-5.0.3.jar:5.0.3]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.9.3.jar:na]
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[okhttp-4.9.3.jar:na]
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517) ~[okhttp-4.9.3.jar:na]
	... 3 common frames omitted
	Suppressed: java.net.SocketTimeoutException: connect timed out
		... 31 common frames omitted

```
 I believe I need a proxy to send message to line server and found a simple doc without example: https://github.com/line/line-bot-sdk-java#how-do-i-use-a-proxy-server

Could you add doc about using `LineMessagingServiceBuilder` to enable proxy in line-bot-spring-boot

**Comment by jiangying000** [comment]
I can use -DsocksProxyHost=localhost -DsocksProxyPort=1080 to enable global proxy in JVM, but is not a good solution enough

**Comment by tokuhirom** [comment]
Sample code to use proxy was already added.
