### ISSUE TITLE
Integrate to Spring Boot with Spring Security

### ISSUE THREAD

**Issue by TommyYehCool** [line/line-bot-sdk-java#96]
Do you ever try to integrate this to Spring Boot which included Spring Security,

I try to do this got exception as below:

```
[2017-03-08 22:20:21.129][http-nio-8080-exec-1][ERROR][o.a.c.c.C.[.[.[.[dispatcherServlet]] Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.ClassCastException: org.springframework.web.servlet.mvc.ParameterizableViewController cannot be cast to org.springframework.web.method.HandlerMethod] with root cause
java.lang.ClassCastException: org.springframework.web.servlet.mvc.ParameterizableViewController cannot be cast to org.springframework.web.method.HandlerMethod
	at com.linecorp.bot.spring.boot.interceptor.LineBotServerInterceptor.preHandle(LineBotServerInterceptor.java:49)
	at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:134)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:958)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
```

**Comment by kazuki-ma** [comment]
Thank you for your feedback.
First, could you give me more detail about your propose?

I think you have to hosting "event callback endpoint" and "public resources" in same server
and want to protect your public resources by Spring Security.

Is it right?

**Comment by TommyYehCool** [comment]
Yea it is right

**Comment by kazuki-ma** [comment]
OK but sorry I can't reproduce your issue.

Please be careful you should `security.ignored: /callback`.

Could you give me the code to reproduces?

Below is the code for my test.

# My java
```java
package com.example.bot.spring.echo;

import java.security.Principal;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import com.linecorp.bot.model.event.Event;
import com.linecorp.bot.model.event.MessageEvent;
import com.linecorp.bot.model.event.message.TextMessageContent;
import com.linecorp.bot.model.message.TextMessage;
import com.linecorp.bot.spring.boot.annotation.EventMapping;
import com.linecorp.bot.spring.boot.annotation.LineMessageHandler;

import lombok.extern.slf4j.Slf4j;

@SpringBootApplication
@LineMessageHandler
@RestController
@Slf4j
public class EchoApplication extends WebSecurityConfigurerAdapter {
    public static void main(String[] args) {
        SpringApplication.run(EchoApplication.class, args);
    }

    @GetMapping("/")
    public Object whoami(final Principal principal)  {
        return principal;
    }

    @EventMapping
    public TextMessage handleTextMessageEvent(
            final MessageEvent<TextMessageContent> event) {
        return new TextMessage(event.getMessage().getText());
    }

    @EventMapping
    public void handleDefaultMessageEvent(final Event event) {
        log.info("Event: {}", event);
    }
}
```

# application.yml
```yml
line.bot:
  channel-secret: MY SECRET
  channel-token: MY TOKEN

security:
  ignored: /callback
```

**Comment by TommyYehCool** [comment]
I think that I missed the setting, thanks for your help!

**Comment by kazuki-ma** [comment]
You are welcome~
